/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __com_p6majo_math_nswc_NswcMath__
#define __com_p6majo_math_nswc_NswcMath__

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT void JNICALL Java_com_p6majo_math_nswc_NswcMath_mycgamma (JNIEnv *env, jobject, jdoubleArray, jdoubleArray);
JNIEXPORT void JNICALL Java_com_p6majo_math_nswc_NswcMath_mycloggamma (JNIEnv *env, jobject, jdoubleArray, jdoubleArray);
JNIEXPORT void JNICALL Java_com_p6majo_math_nswc_NswcMath_mycbesselj (JNIEnv *env, jobject, jdoubleArray, jdoubleArray, jdoubleArray);
JNIEXPORT void JNICALL Java_com_p6majo_math_nswc_NswcMath_mybesselj (JNIEnv *env, jobject, jint, jdoubleArray, jdoubleArray);
JNIEXPORT jint JNICALL Java_com_p6majo_math_nswc_NswcMath_myellipticcomplex (JNIEnv *env, jobject, jdoubleArray, jfloat, jfloat, jdoubleArray, jdoubleArray, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif

#endif /* __com_p6majo_math_nswc_NswcMath__ */
