/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_p6majo_math_nswc_NswcMath */

#ifndef _Included_com_p6majo_math_nswc_NswcMath
#define _Included_com_p6majo_math_nswc_NswcMath
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_p6majo_math_nswc_NswcMath
 * Method:    mycgamma
 * Signature: ([D[D)V
 */
JNIEXPORT void JNICALL Java_com_p6majo_math_nswc_NswcMath_mycgamma
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray);

/*
 * Class:     com_p6majo_math_nswc_NswcMath
 * Method:    mycloggamma
 * Signature: ([D[D)V
 */
JNIEXPORT void JNICALL Java_com_p6majo_math_nswc_NswcMath_mycloggamma
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray);

/*
 * Class:     com_p6majo_math_nswc_NswcMath
 * Method:    mycbesselj
 * Signature: ([D[D[D)V
 */
JNIEXPORT void JNICALL Java_com_p6majo_math_nswc_NswcMath_mycbesselj
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     com_p6majo_math_nswc_NswcMath
 * Method:    mybesselj
 * Signature: (I[D[D)V
 */
JNIEXPORT void JNICALL Java_com_p6majo_math_nswc_NswcMath_mybesselj
  (JNIEnv *, jobject, jint, jdoubleArray, jdoubleArray);

/*
 * Class:     com_p6majo_math_nswc_NswcMath
 * Method:    myellipticcomplex
 * Signature: ([DFF[D[D[DI)I
 */
JNIEXPORT jint JNICALL Java_com_p6majo_math_nswc_NswcMath_myellipticcomplex
  (JNIEnv *, jobject, jdoubleArray, jfloat, jfloat, jdoubleArray, jdoubleArray, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
